<?php

global $idtipcur_nom_ofer;
global $idequi_idtipcur_ofer_seek;
global $idtipcur_nom_seek;
global $idmet_nom_ofer;
global $idequi_idmet_ofer_seek;
global $idmet_nom_seek;
global $idcer_nom_ofer;
global $idestudi_nom_ofer;
global $eqip_of_seek;

$eqip_of_seek[115]="15";
$eqip_of_seek[114]="03";
$eqip_of_seek[83]="01";
$eqip_of_seek[116]="02";
$eqip_of_seek[117]="04";
$eqip_of_seek[118]="33";
$eqip_of_seek[84]="05";
$eqip_of_seek[105]="06";
$eqip_of_seek[113]="07";
$eqip_of_seek[104]="08";
$eqip_of_seek[103]="09";
$eqip_of_seek[102]="10";
$eqip_of_seek[101]="11";
$eqip_of_seek[109]="39";
$eqip_of_seek[119]="12";
$eqip_of_seek[134]="51";
$eqip_of_seek[112]="13";
$eqip_of_seek[120]="14";
$eqip_of_seek[100]="16";
$eqip_of_seek[111]="17";
$eqip_of_seek[121]="18";
$eqip_of_seek[99]="19";
$eqip_of_seek[98]="20";
$eqip_of_seek[122]="21";
$eqip_of_seek[97]="22";
$eqip_of_seek[110]="23";
$eqip_of_seek[123]="26";
$eqip_of_seek[132]="35";
$eqip_of_seek[124]="24";
$eqip_of_seek[85]="25";
$eqip_of_seek[125]="27";
$eqip_of_seek[126]="28";
$eqip_of_seek[127]="29";
$eqip_of_seek[133]="52";
$eqip_of_seek[128]="30";
$eqip_of_seek[96]="31";
$eqip_of_seek[86]="32";
$eqip_of_seek[129]="34";
$eqip_of_seek[95]="36";
$eqip_of_seek[94]="37";
$eqip_of_seek[130]="38";
$eqip_of_seek[131]="40";
$eqip_of_seek[93]="41";
$eqip_of_seek[92]="42";
$eqip_of_seek[108]="43";
$eqip_of_seek[91]="44";
$eqip_of_seek[90]="45";
$eqip_of_seek[107]="46";
$eqip_of_seek[87]="47";
$eqip_of_seek[106]="48";
$eqip_of_seek[89]="49";
$eqip_of_seek[88]="50";	
	

$idtipcur_nom_ofer[21]="Apuntes";
$idtipcur_nom_ofer[14]="Carreras universitarias";
$idtipcur_nom_ofer[33]="Ciclo grado medio";
$idtipcur_nom_ofer[12]="Ciclo Grado Superior";
$idtipcur_nom_ofer[3]="Curso";
$idtipcur_nom_ofer[32]="Curso técnico";
$idtipcur_nom_ofer[24]="Cursos de doctorado";
$idtipcur_nom_ofer[23]="Cursos de Verano";
$idtipcur_nom_ofer[28]="Diplomatura";
$idtipcur_nom_ofer[15]="Doctorado";
$idtipcur_nom_ofer[31]="Experto";
$idtipcur_nom_ofer[19]="Feria";
$idtipcur_nom_ofer[13]="Formación a empresas";
$idtipcur_nom_ofer[9]="Formación Ocupacional";
$idtipcur_nom_ofer[11]="Formación Profersional";
$idtipcur_nom_ofer[27]="Formación subvencionada";
$idtipcur_nom_ofer[17]="Jornadas y conferencias";
$idtipcur_nom_ofer[29]="Licenciatura";
$idtipcur_nom_ofer[7]="Manual";
$idtipcur_nom_ofer[1]="Master";
$idtipcur_nom_ofer[4]="Monografía";
$idtipcur_nom_ofer[25]="Ocupacional";
$idtipcur_nom_ofer[6]="Oposiciones";
$idtipcur_nom_ofer[16]="Otros estudios";
$idtipcur_nom_ofer[5]="Postgrado";
$idtipcur_nom_ofer[8]="Seminario";
$idtipcur_nom_ofer[18]="Taller";
$idtipcur_nom_ofer[10]="Tutorial";
$idtipcur_nom_ofer[20]="White Paper";

$idequi_idtipcur_ofer_seek[3]=1;$idtipcur_nom_seek[1]="Curso";
$idequi_idtipcur_ofer_seek[1]=2;$idtipcur_nom_seek[2]="Master";
$idequi_idtipcur_ofer_seek[5]=3;$idtipcur_nom_seek[3]="Postgrado";
$idequi_idtipcur_ofer_seek[6]=4;$idtipcur_nom_seek[4]="Oposiciones";
$idequi_idtipcur_ofer_seek[11]=5;$idtipcur_nom_seek[5]="Formación Profesional";
$idequi_idtipcur_ofer_seek[33]=6;$idtipcur_nom_seek[6]="Ciclo grado medio";
$idequi_idtipcur_ofer_seek[12]=7;$idtipcur_nom_seek[7]="Ciclo Grado Superior";
$idequi_idtipcur_ofer_seek[14]=8;$idtipcur_nom_seek[8]="Carreras universitarias";
$idequi_idtipcur_ofer_seek[32]=9;$idtipcur_nom_seek[9]="Curso técnico";
$idequi_idtipcur_ofer_seek[24]=10;$idtipcur_nom_seek[10]="Cursos de doctorado";
$idequi_idtipcur_ofer_seek[23]=11;$idtipcur_nom_seek[11]="Cursos de Verano";
$idequi_idtipcur_ofer_seek[28]=12;$idtipcur_nom_seek[12]="Diplomatura";
$idequi_idtipcur_ofer_seek[15]=13;$idtipcur_nom_seek[13]="Doctorado";
$idequi_idtipcur_ofer_seek[31]=14;$idtipcur_nom_seek[14]="Experto";
$idequi_idtipcur_ofer_seek[19]=15;$idtipcur_nom_seek[15]="Feria";
$idequi_idtipcur_ofer_seek[13]=16;$idtipcur_nom_seek[16]="Formación a empresas";
$idequi_idtipcur_ofer_seek[9]=17;$idtipcur_nom_seek[17]="Formación Ocupacional";
$idequi_idtipcur_ofer_seek[27]=18;$idtipcur_nom_seek[18]="Formación subvencionada";
$idequi_idtipcur_ofer_seek[17]=19;$idtipcur_nom_seek[19]="Jornadas y conferencias";
$idequi_idtipcur_ofer_seek[29]=20;$idtipcur_nom_seek[20]="Licenciatura";
$idequi_idtipcur_ofer_seek[7]=21;$idtipcur_nom_seek[21]="Manual";
$idequi_idtipcur_ofer_seek[4]=22;$idtipcur_nom_seek[22]="Monografía";
$idequi_idtipcur_ofer_seek[25]=23;$idtipcur_nom_seek[23]="Ocupacional";
$idequi_idtipcur_ofer_seek[16]=24;$idtipcur_nom_seek[24]="Otros estudios";
$idequi_idtipcur_ofer_seek[8]=25;$idtipcur_nom_seek[25]="Seminario";
$idequi_idtipcur_ofer_seek[18]=26;$idtipcur_nom_seek[26]="Taller";
$idequi_idtipcur_ofer_seek[10]=27;$idtipcur_nom_seek[27]="Tutorial";
$idequi_idtipcur_ofer_seek[20]=28;$idtipcur_nom_seek[28]="White Paper";
$idequi_idtipcur_ofer_seek[21]=29;$idtipcur_nom_seek[29]="Apuntes";


$idmet_nom_ofer[1]="Presencial";
$idmet_nom_ofer[2]="Personalizado";
$idmet_nom_ofer[3]="Online";
$idmet_nom_ofer[4]="A Distancia";
$idmet_nom_ofer[5]="Vídeo";
$idmet_nom_ofer[6]="CD ROM";
$idmet_nom_ofer[7]="Semipresencial";
$idmet_nom_ofer[8]="Otros";
$idmet_nom_ofer[9]="En el extranjero";


$idequi_idmet_ofer_seek[1]=1;$idmet_nom_seek[1]="Presencial";
$idequi_idmet_ofer_seek[7]=2;$idmet_nom_seek[2]="Semipresencial";
$idequi_idmet_ofer_seek[2]=3;$idmet_nom_seek[3]="Personalizado";
$idequi_idmet_ofer_seek[4]=4;$idmet_nom_seek[4]="A Distancia";
$idequi_idmet_ofer_seek[3]=5;$idmet_nom_seek[5]="Online";
$idequi_idmet_ofer_seek[9]=6;$idmet_nom_seek[6]="En el extranjero";
$idequi_idmet_ofer_seek[5]=7;$idmet_nom_seek[7]="Vídeo";
$idequi_idmet_ofer_seek[6]=8;$idmet_nom_seek[8]="CD ROM";
$idequi_idmet_ofer_seek[8]=9;$idmet_nom_seek[9]="Otros";

$idcer_nom_ofer[1]="Certificado";
$idcer_nom_ofer[2]="Homologado";
$idcer_nom_ofer[3]="Autorizado";
$idcer_nom_ofer[4]="Titulación Oficial";
$idcer_nom_ofer[5]="Preparación Oficial";
$idcer_nom_ofer[6]="Título Propio";
$idcer_nom_ofer[7]="Homologable";
$idcer_nom_ofer[8]="Convalidación";
$idcer_nom_ofer[9]="Otros";
$idcer_nom_ofer[10]="Acreditado";

$idestudi_nom_ofer[1]="Sin Estudios";
$idestudi_nom_ofer[10]="Certificado escolaridad";
$idestudi_nom_ofer[11]="Graduado escolar / EGB / 2ºBUP";
$idestudi_nom_ofer[12]="ESO";
$idestudi_nom_ofer[21]="FP I / Grado Medio";
$idestudi_nom_ofer[23]="B.LOGSE / COU";
$idestudi_nom_ofer[41]="FP II / Grado Superior";
$idestudi_nom_ofer[51]="Diplomado";
$idestudi_nom_ofer[61]="Licenciado";
$idestudi_nom_ofer[71]="Doctor";


?>